version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'admin@123'
      MYSQL_ROOT_PASSWORD: 'admin@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./volume/mysql-db:/var/lib/mysql
