version: '3.3'

services:
  postgresdb:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes: 
      - ./volume/postgres-db:/var/lib/mysql